Test
codecaiine/math-magicians pull request #7
Opened 2021-09-30 14:22 UTC by emmanuellekamwa

In this project, we have: 
- Written unit tests for the files `operate.js` and `calculate.js` using Jest.
- Created unit tests for all React components

2021-09-30 14:34 UTC, mikenath223 requested changes
Hello  

You've done pretty well so far!
But for a few issues, you are almost done with this. Hang in there!


## Required Changes ♻️
_Please check the comments under the review._

Happy coding, Cheers! 🚀🚀

Do feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, whether it is valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-30 14:35 UTC, mikenath223 commented
- [ ] One test case fails kindly check and fix it.

2021-09-30 14:36 UTC, mikenath223 commented on src/__tests__/calculate.test.js
> +    item = { ...item, ...calculate(item, '8') };
- [ ] You have the calculate test in both `tests` and `__tests__` kindly remove one of the test files.

2021-09-30 14:37 UTC, mikenath223 commented on src/__tests__/operate.test.js
> +    const b = 2;
- [ ] You also have the operate.test.js duplicated in multiple directories; `tests` and `__tests__`, please remove one of the test files.

2021-09-30 14:37 UTC, mikenath223 commented on src/__tests__/operate.test.js
> +    expect(answer).toBe('3');
- [ ] Kindly include a test case for division by zero.

2021-10-01 08:43 UTC, mke2111 approved these changes
### Hi @emmanuellekamwa & @codecaiine, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
**Congratulations! 🎉** 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-01 08:47 UTC, merged